### ISSUE TITLE
Question: Coin battery Fork

### ISSUE THREAD

**Issue by rafaeldelboni** [rtitmuss/tornblue#3]
I was planning to build this project to make a single PCB keyboard with choc switches (ferris like), but with the current battery is very hard to have something nice looking without the case.

So I was thinking to fork this and replace the current battery and use a coin battery in the space of the rotary encoder.

Lithium Battery CR2032 210mAh
https://a.aliexpress.com/_mOBfcmy

Battery Holder
https://a.aliexpress.com/_mt0Ty5w

Do you think is possible? How hard would be?

**Comment by rtitmuss** [comment]
I don't think that would work, as these are non rechargeable batteries (any
maybe also the wrong voltage). You would need to make significant changes,
for example removing the battery charging chip. I would also be concerned
about the battery life. There are some keyboards that use a CR2032, and I
think these are typically paired with a dongle.

I did consider using a LIR2032, which is rechargeable, but it had a very
big footprint and didn't work atheistically.

**Comment by rafaeldelboni** [comment]
Thanks for the clarification and all your work for the community.
